version: '3'

services:
  concierge-1:
    container_name: concierge-1
    image: marnikita/concierge
    ports:
      - 8080:8080
    environment:
      - CONCIERGES=concierge-1,concierge-2,concierge-3
      - HOST=concierge-1

  concierge-2:
    container_name: concierge-2
    image: marnikita/concierge
    environment:
      - CONCIERGES=concierge-1,concierge-2,concierge-3
      - HOST=concierge-2

  concierge-3:
    container_name: concierge-3
    image: marnikita/concierge
    environment:
      - CONCIERGES=concierge-1,concierge-2,concierge-3
      - HOST=concierge-3

