version: '3'

services:
  concierge-1:
    container_name: concierge-1
    image: marnikita/concierge
    ports:
      - 8080:8080
    environment:
      - HOST=concierge-1
      - CONCIERGES=["concierge-1:23456","concierge-2:23456","concierge-3:23456"]
      - ACTOR_PORT=23456
      - CLIENT_PORT=8080

  concierge-2:
    container_name: concierge-2
    image: marnikita/concierge
    ports:
      - 8081:8080
    environment:
      - HOST=concierge-2
      - CONCIERGES=["concierge-1:23456","concierge-2:23456","concierge-3:23456"]
      - ACTOR_PORT=23456
      - CLIENT_PORT=8080

  concierge-3:
    container_name: concierge-3
    image: marnikita/concierge
    ports:
      - 8082:8080
    environment:
      - HOST=concierge-3
      - CONCIERGES=["concierge-1:23456","concierge-2:23456","concierge-3:23456"]
      - ACTOR_PORT=23456
      - CLIENT_PORT=8080

